### PR TITLE
Share terminal width with child processes

### PR DESCRIPTION
**Pull request by jviotti**
Currently, `cli-width` reports `0` (the default value) within scripts
called by `windosu`.

Test:

```js
// test.js
var cliWidth = require('cli-width');
console.log(cliWidth());
```

***

```sh
> node bin\sudo node test.js
120
```

Fixes: https://github.com/tehsenaus/windosu/issues/4

### CODE REVIEW

**Comment by jviotti** [comment]
The generated JavaScript is very different to the commited one. Could it be because it was compiled with an older Latte version? I'm happy to re-compile with a specific version so the diff is a little bit cleaner and reflects the changes better if you like.

**Comment by jviotti** [comment]
I wasn't able to test running as another user though.

I've tried:

```js
windosu.exec('node test.js', {

    // The username according to my PC
    user: 'Juan Cruz Viotti'
})
```

But I see nothing on the screen after executing. Am I missing something?

**Comment by tehsenaus** [comment]
Thanks for this - I'll review it on Monday when I have access to a Windows machine.

I can't remember if the switch user ever worked. Does it work on the original verison?

**Comment by jviotti** [comment]
@tehsenaus I have no idea, but will give it a test on Monday as well!

**Comment by jviotti** [comment]
@tehsenaus I've tested the switch user functionality from `master`, and it doesn't seem to work neither.

**Comment by jviotti** [comment]
@tehsenaus Did you have a change to look at this PR? Let me know if I should do anything!

**Comment by tehsenaus** [comment]
Sorry for the delay. I'll release a new version this evening!

**Pull request merged**
